pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:demo-migration12/demo testing.git
          - cd demo testing.git
          - git push --mirror git@github.com:asaphdanchi/demo-g.git