pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone https://x-token-auth:ATCTT3xFfGN0vM0DPOMT1a96MKkxRglKkzM8QCIfZgENQeKoaeTVS4vWXwZA-0jZSrHjKo7-YABtzn6GpIKcGMTS1Ix2uZ5cDjhKgqiHOE-FAsRQheMLKEp_vR3w4mU0qAijyuNafXYKJbPUiKpiiWv23RIYRDOymiTOOOS0ZWMRsQuUlhzB8C8=D40524DE@bitbucket.org/demo-migration12/demo-testing.git
          - cd demo-testing
          - git push --mirror https://x-token-auth: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@github.com/asaphdanchi/demo-g.git