
apiVersion: apps/v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-sa
  namespace: ingress-nginx

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: my-role
  namespace: ingress-nginx
rules:
- apiGroups: ["extensions", "apps", "batch"]
  resources: ["deployments", "jobs", "daemonsets"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
  namespace: ingress-nginx
subjects:
- kind: ServiceAccount
  name: nginx-ingress-sa
  namespace: ingress-nginx
roleRef:
  kind: Role
  name: my-role
  apiGroups: rbac.authorization.k8s.io/v1

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  selector:
    matchLabels:
      app: nginx-ingress-controller
  template:
    metadata:
      labels:
        app: nginx-ingress-controller
    spec:
      nodeSelector:
        kubernetes.io/hostname: dmasaph
      serviceAccountName: nginx-ingress-sa
      containers:
        - name: nginx-ingress-controller
          image: nginx/nginx-ingress-controller:latest
          command: ["nginx", "-s", "reload"]

---

pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone https://x-token-auth:"$bitbucket_access"@bitbucket.org/demo-migration12/demo-testing.git
          - cd demo-testing
          - git push --mirror https://x-token-auth:"$github_repo"@github.com/asaphdanchi/demo-g.git